### ISSUE TITLE
Provide access to underlying HTTP client

### ISSUE THREAD

**Issue by estahn** [fern-api/fern-python#275]
We should be able to access the underlying HTTP Client for various reasons:

* Mocking
* Attaching persistent headers, e.g. token auth
* Custom features like rate-limiting

https://www.python-httpx.org/advanced/#sharing-configuration-across-requests

> If you do anything more than experimentation, one-off scripts, or prototypes, then you should use a Client instance.

**Comment by dsinghvi** [comment]
@estahn how would you imagine the code generation looks? would you want to pass in your own `httpx` client? or would you rather the client expose the relevant fields like headers + rate-limiting?

**Comment by estahn** [comment]
Initially, I thought I was just on the wrong version after glimpsing at this https://github.com/fern-api/fern-python/blob/e4ae84b72c3dc4fc8c55b45f48fabf506be58f53/tests/sdk/snapshots/snap_test_sdk/test_trace_sdk%20client.py#L30

I don't have strong preferences, I would have guessed mocking requires to inject the client, but seems like that is not necessary https://colin-b.github.io/pytest_httpx/

```
client = MyApi(content_type="application/json")
token = client.login(...)

client.httpClient().addHeader("Authorization", f"Bearer {token}")
```

Something like that. Not sure if that works with httpx.

**Comment by dsinghvi** [comment]
@estahn you should be able to do this in the latest sdk generator [0.3.8-rc3](https://github.com/fern-api/fern-python/releases/tag/0.3.8-rc3). 

Here's an example: 
```python

client = MyApi(<args>);
client._client_wrapper.httpx_client // now you have access to the underlying httpx client
```

**Comment by estahn** [comment]
@dsinghvi 
```
  File ".../generated/sungrow_sdk/core/jsonable_encoder.py", line 20, in <module>
    from pydantic.json import ENCODERS_BY_TYPE
ImportError: cannot import name 'ENCODERS_BY_TYPE' from 'pydantic.json' (/usr/local/lib/python3.9/site-packages/pydantic/json.py)
```

![image](https://github.com/fern-api/fern-python/assets/362174/9c00850b-c25b-4b33-a421-6e1fae3b7b58)

**Comment by estahn** [comment]
@dsinghvi I changed `jsonable_encoder.py` to

```
try:
    from pydantic.json import ENCODERS_BY_TYPE
except ImportError:
    from pydantic.deprecated.json import ENCODERS_BY_TYPE
```

Now it runs, but still some warnings:

```
/usr/local/lib/python3.9/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'json_encoders' has been removed
  warnings.warn(message, UserWarning)
/usr/local/lib/python3.9/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'json_encoders' has been removed
  warnings.warn(message, UserWarning)
```

**Comment by estahn** [comment]
@dsinghvi Not sure if I'm misreading this, but the `client` is not actually used in the requests in my option.

Imo the below should be `_response = self._client.request(`

![image](https://github.com/fern-api/fern-python/assets/362174/b48a98d8-83fb-421d-8a92-41aecff328c2)

**Comment by dsinghvi** [comment]
@estahn my fault, i gave you the wrong version to try this with. If you try it with `0.3.8-rc3-2-g3608f9de` does it work?

**Comment by dsinghvi** [comment]
If so, I'll release that version

**Comment by estahn** [comment]
@dsinghvi Looks like the above is working with the mentioned version.
