### ISSUE TITLE
Allow specifying `base_url` instead of a static Environment

### ISSUE THREAD

**Issue by markphelps** [fern-api/fern-python#279]
To support cases where the base url is not always know (ie users running self hosted versions) of the API

From Discord: https://discord.com/channels/988611740499574794/1121510960327303219/1121511027549409362

@dsinghvi  suggested the following API:

> If you use an environment, you use the enum: 
```
flipt_client = FliptAPI(
  environment=Environment.Production, # or Environment.Staging
);
```

> If you want your own URL, you pass a base_url : 
```
flipt_client = FliptAPI(
  base_url="https://wwww.selfhosted.flipt.com",
);
```

**Comment by markphelps** [comment]
@dsinghvi gentle ping. Any update on this?

**Comment by dsinghvi** [comment]
sorry, this slipped through the cracks @markphelps. will report back tomorrow

**Comment by dsinghvi** [comment]
**Outlining plan for implementation:** 

If no environment: 
- client should only provide a base_url argument

If single url environment and no default environment: 
 - client should provide a base_url argument
 - client should error if the user provides both environment and default
 
If single url environment and default environment: 
 - client should provide a base_url argument
 - client prefers base_url over environment

If multi url environment:  
  - client should provide a multi url environment argument
