### ISSUE TITLE
OpenAPI: Misleading "File download is not supported" error w/o specifying any "file download response"

### ISSUE THREAD

**Issue by miwurster** [fern-api/fern-python#282]
Hey guys, I'm testing fern currently to generate SDKs for our API. I followed the steps in the documentation on how to generate an SDK from an existing OpenAPI spec. Unfortunately, I get the following error when using the Python SDK generator:

```
[api]: fernapi/fern-python-sdk File download is not supported.
```

I do not really understand what this error means. From digging into the Docker logs while using `--local --keepDocker` I assume at the moment that the generator identifies one or more `application/octet-stream` responses and those are not supported at the moment. Am I on the right track?

However, my OpenAPI spec does not declare any "file download response". For testing, I defined three routes, a `POST` method with a `text/plain response`, a `GET` method with a `text/plain` response and a `GET` method with a `appliation/json response`. Btw, the node-sdk generator works just fine with this OpenAPI spec.

Here is the OpenAPI spec:
[api-spec-service.json.zip](https://github.com/fern-api/fern/files/11968904/api-spec-service.json.zip)

**Comment by dsinghvi** [comment]
@miwurster for now can you comment out the `"/v1/hqp/job/{id}/status"` endpoint or the response? We don't support generating `text/plain` currently in the Python generator which is the root cause for the error.

**Comment by miwurster** [comment]
Ok good to know. 

Do you guys have an overview of what each generator supports at the moment? This would be very helpful I think.


However, I think we can close this issue for now.

**Comment by dsinghvi** [comment]
Hey @miwurster we are working on that update. I am actually merging https://github.com/fern-api/fern-python/pull/294 which should add file download support and the generated code should match your expectations.

**Comment by dannysheridan** [comment]
fixed
