### ISSUE TITLE
Support for async path definitions

### ISSUE THREAD

**Issue by armandobelardo** [fern-api/fern-python#283]
Hi there!

At Mammoth we leverage the SQLAlchemy async engine to be able to do non-blocking DB transactions, so almost all of our endpoints would typically be async. 

Right now, if you were to make the overridden abstract function async, you'll get an error as the return types do not match the base ABC
![image](https://github.com/fern-api/fern-python/assets/11140328/59f9873f-ff88-426a-bddf-b8bd712b06af)
![image](https://github.com/fern-api/fern-python/assets/11140328/c18507a4-bafe-488b-8765-b0c288216e9d)

Workaround I'm going to be using:

> I _think_ I can get the benefits of SQLAlchemy asyncio in terms of async transactions by just using: https://github.com/sqlalchemy/sqlalchemy/discussions/5923
> 
> And FastAPI should still deal with the non-async path definition in a non-blocking way: https://fastapi.tiangolo.com/async/#path-operation-functions
```
class ReferencesClient(AbstractReferenceReferencesService):
    def __init__(self, session: AsyncSession = Depends(get_db_session)):
        self.session = session

    def create_reference(
        self, *, body: CreateReferenceRequest, auth: ApiAuth
    ) -> ReferenceId:
        return references.create_reference(
            body,
            session=self.session,
        ).send(None)

```

Discord thread for additional context: https://discord.com/channels/988611740499574794/988611741476859916/1126685270692089916

**Comment by dsinghvi** [comment]
## Proposal for implementaiton

- Add a `async: boolean` config to the FastAPI generator [here](https://github.com/fern-api/fern-python/blob/main/src/fern_python/generators/fastapi/custom_config.py)
- If this config is true then all abstract endpoint methods should be async ([code](https://github.com/fern-api/fern-python/blob/a35c327936acb8837efcdd7b006145535f0d0baa/src/fern_python/generators/fastapi/service_generator/endpoint_generator.py#L64-L72))

@armandobelardo @GfxKai

**Comment by armandobelardo** [comment]
Thank you!
<img src="https://b2455576.smushcdn.com/2455576/wp-content/uploads/2020/10/guy-fieri-chefs-kiss.gif"/>
