### ISSUE TITLE
Support pydantic 2

### ISSUE THREAD

**Issue by estahn** [fern-api/fern-python#288]
The following allows support for pydantic 2

`jsonable_encoder.py`:

```
try:
    from pydantic.json import ENCODERS_BY_TYPE
except ImportError:
    from pydantic.deprecated.json import ENCODERS_BY_TYPE
```

Now it runs, but still some warnings:

```
/usr/local/lib/python3.9/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'json_encoders' has been removed
  warnings.warn(message, UserWarning)
/usr/local/lib/python3.9/site-packages/pydantic/_internal/_config.py:261: UserWarning: Valid config keys have changed in V2:
* 'allow_population_by_field_name' has been renamed to 'populate_by_name'
* 'json_encoders' has been removed
  warnings.warn(message, UserWarning)
```

_Originally posted by @estahn in https://github.com/fern-api/fern-python/issues/275#issuecomment-1623334152_

**Comment by logan-markewich** [comment]
+1 -- you can even support this under the hood with their compatibility layer while waiting for the ecosystem to migrate

`from pydantic.v1 import ...`

**Comment by logan-markewich** [comment]
+1 -- this is an easy fix it seems

**Comment by dsinghvi** [comment]
https://github.com/fern-api/fern-python/releases/tag/0.6.0-rc0 I've just released an rc version of the generator that will generate imports that are compatible with both pydantic v1 and v2, if you can give it a spin that would be great!

**Comment by AvikantSrivastava** [comment]
any update on this?

**Comment by dsinghvi** [comment]
@AvikantSrivastava this is rolled out in the latest version of the generator! I'm going to close this and reopen if you have issues.
