### ISSUE TITLE
Regression: multiple response types

### ISSUE THREAD

**Issue by estahn** [fern-api/fern-python#317]
We have receive multiple formats from an API and I was under the impression this worked before. I believe the code would try to run pydantic and if its not valid it would try the next class.

Has this been removed?

This is there response definition:

![image](https://github.com/fern-api/fern-python/assets/362174/e39fd778-d749-489f-9b24-53ad2b2f494b)

**Comment by dsinghvi** [comment]
@estahn this should still work, what behavior are you seeing ?
